### ISSUE TITLE
How to deal with NULLs

### ISSUE THREAD

**Issue by proofrock** [cvilsmeier/sqinn-go#2]
Hi,
   first of all, thanks for your work. The concept is wonderful and it works well. I have one question though: how to tell that a result of a query is NULL - or it's (for example) zero.

```
rows, _ := sq.Query("SELECT val FROM tabl", []interface{}{}, []byte{sqinn.ValInt})
// How to tell if rows[0].Values[0] is NULL or 0?
```

Maybe a method like rows[0].IsNull(0) could be useful. Of course, if I am not missing something.

**Comment by cvilsmeier** [comment]
You might want to use a value's `Set` boolean property, like so:

	rows, _ := sq.Query("SELECT val FROM tabl", nil, []byte{sqinn.ValInt})
	for _, row := range rows {
		val := row.Values[0].Int
		if val.Set {
			log.Print("value is set (not NULL): ", val.Value)
		} else {
			log.Print("value is NULL")
		}
	}

**Comment by proofrock** [comment]
Thanks, works fine! You can close it. Is it somewhere in the docs? I may have missed it.

**Comment by cvilsmeier** [comment]
I think you're right: Docs should be more precise here.
[https://pkg.go.dev/github.com/cvilsmeier/sqinn-go/sqinn#IntValue](https://pkg.go.dev/github.com/cvilsmeier/sqinn-go/sqinn#IntValue)
Reopening issue.

**Comment by cvilsmeier** [comment]
Added example for handling NULL values, see file `sqinn/sqinn_examples_test.go`.
