### ISSUE TITLE
Convenient way of passing NULLs to queries

### ISSUE THREAD

**Issue by proofrock** [cvilsmeier/sqinn-go#3]
Hi,
   what is the idiomatic way of passing a `nil` in a `[]interface{}`? I tried the following:

```
type test struct {
	TestVal *int
}

sq, _ := sqinn.Launch(sqinn.Options{
		SqinnPath: "../env/sqinn",
	})
	defer sq.Terminate()

	sq.Open("../env/test.db")
	defer sq.Close()

	sq.ExecOne("create table tbl (col int null)")

	value := 17
	tst := test{}

	tst.TestVal = &value

	_, err := sq.Exec("INSERT INTO tbl(col) VALUES(?)", 1, 1, []interface{}{tst.TestVal})
	if err != nil {
		commons.Panic(fiber.StatusInternalServerError, fmt.Sprintf("Query 1 failed: %v\n", err))
	}

	tst.TestVal = nil

	_, err = sq.Exec("INSERT INTO tbl(col) VALUES(?)", 1, 1, []interface{}{tst.TestVal})
	if err != nil {
		commons.Panic(fiber.StatusInternalServerError, fmt.Sprintf("Query 2 failed: %v\n", err))
	}
```

The first one fails, because `cannot bind type *int`, and actually it should be `int`, that is simply what I used to do with PostgreSQL. If I pass a `int` as a variable, on the other hand, I have no way to pass a `nil` in the same variable (say, if the variable is loaded from JSON for example, I might have this situation).

Admittedly, this is probably an issue of mine with Go, not with the library in particular.

Thank you!

**Comment by proofrock** [comment]
I have implemented a function that goes through a slice of `interface{}` and dereferences pointers if they are not null. I strongly suspect that there is a better way ;-) also because I have to list types manually. I am not a black belt of Go.

```
func deref(iarr []interface{}) []interface{} {
	for i := 0; i < len(iarr); i++ {
		if reflect.ValueOf(iarr[i]).Kind() == reflect.Ptr {
			if iarr[i] != nil {
				if reflect.ValueOf(iarr[i]).IsNil() {
					iarr[i] = nil
				} else {
					switch iarr[i].(type) {
					case *int:
						iarr[i] = *iarr[i].(*int)
						break
					case *string:
						iarr[i] = *iarr[i].(*string)
						break
					case *float64:
						iarr[i] = *iarr[i].(*float64)
						break
					}
				}
			}
		}
	}
	return iarr
}
```

To apply:

```
_, err = sq.Exec("INSERT INTO tbl(col) VALUES(?)", 1, 1, deref([]interface{}{tst.TestVal}))
```

**Comment by cvilsmeier** [comment]
Maybe like so: <https://gist.github.com/cvilsmeier/30114a9f1ebde5322a8335e0daf62193>

**Comment by proofrock** [comment]
Thanks!
