### ISSUE TITLE
Remove "pure Go" claim

### ISSUE THREAD

**Issue by 89z** [cvilsmeier/sqinn-go#4]
I found this package via an internet search for "pure golang sqlite"

However this package is not that. In fact its actually worse than a solution such as https://github.com/mattn/go-sqlite3, because it actually has to call an executable to do anything. I think any and all claims about this package being "pure Go" should be removed, as its misleading at best.

**Comment by cvilsmeier** [comment]
Well, I get your message. You're right in that sqinn-go depends on external
software ("sqinn" in this case) to access sqlite3 data files. 

However, i would argue that the same is true for many other database drivers:
Take e.g. https://github.com/lib/pq or https://github.com/go-sql-driver/mysql.
These are also "pure Go", at least the authors say so. They do depend
on external software (postgres and mysql daemons and libraries) to read and
write data files, much like sqinn-go depends on sqinn.

What exactly is "pure Go"? To the best of my knowledge, there is no exact
definition of the term.

**Comment by 89z** [comment]
Its pretty simple really. Pure Go would be anything that

1. doesnt rely on an executable file
2. doesnt rely on any third party code from another language

The only exception to this would be something like `syscall`, as technically that is a C interface, but youre calling stuff that is provided by the operating system. Plenty of examples. Here is a read only SQLite implementation in Go [1], and here is another database in pure Go [2].

1. https://github.com/alicebob/sqlittle
2. https://github.com/genjidb/genji

**Comment by cvilsmeier** [comment]
> Pure Go would be anything that
> 1. doesnt rely on an executable file

So you're saying that anything using os/exec is not pure Go?

> 2. doesnt rely on any third party code from another language

Almost all Go programs rely on third party code written in another
language, right? Take for example libc on Linux or kernel32.dll on
Windows, both written in C/C++.

**Comment by 89z** [comment]
It seems you didnt read the paragraph after point 2.

**Comment by cvilsmeier** [comment]
I have read the paragraph, and I'm aware of the projects mentioned therein. Yes, there are packages that read and write sqlite3 database files without any external executables or C code. And yes, there are other database packages written in pure Go. But does that mean that anything using os/exec cannot be pure Go per definitionem?

When os/exec is a no-go, then maybe https://gitlab.com/cznic/sqlite is a good fit.

**Comment by 89z** [comment]
> But does that mean that anything using os/exec cannot be pure Go per definitionem?

Correct. If youre calling some external program, then what you have is just a wrapper for SQLite, or whatever the program may be. Point that its written in Go will be of interest to Go programmers. However people looking for a "pure Go" solution, are people who dont want a package calling any executables, or having to build and/or link any non-system C libraries.

> When os/exec is a no-go, then maybe https://gitlab.com/cznic/sqlite is a good fit.

Thanks, but I dont really need this suggestion, as I already named a few above that I like better.

**Comment by cvilsmeier** [comment]
closed due to age
