### ISSUE TITLE
blatant misuse of the word "pure"

### ISSUE THREAD

**Issue by 1268** [cvilsmeier/sqinn-go#6]
typically using the word "pure", such as "pure Go", implies that the item in question is:

- a Go module
- with no CGO
- with no os/exec

this module is violating one of those items, either intentionally or otherwise. a more accurate description of this project would be "Go module to interact with SQLite executable"

**Comment by 1268** [comment]
THIS, would be a "SQLite with pure Go":

https://gitlab.com/cznic/sqlite

**Comment by cvilsmeier** [comment]
OK, removed 'pure go' claim. Now it reads 'without cgo' instead.
