### ISSUE TITLE
 Golang SQLite without cgo is misleading 

### ISSUE THREAD

**Issue by 1268** [cvilsmeier/sqinn-go#8]
(repost since previous issue was closed without change or comment) 

the current description is still misleading, as the same text could be applied to a project like this:

https://gitlab.com/cznic/sqlite

which is actually a pure Go SQLite module. a better description of this project here would be:

Go module to interact with SQLite executable

**Comment by cvilsmeier** [comment]
After thoughtful consideration I came to the conclusion that 'Golang SQLite without cgo' is technically correct. I will leave it like it is.

**Comment by 1268** [comment]
the issue isn't about whats technically correct, the issue is about whats misleading. have the same description apply to two wholly different projects isn't a good look.
